function [tauLnSdi,phiLnSdi] = interp_STDnonCond(T,para_stdNonCond,RotType,HysType,Cy,Damping)

Periods = [0.030 0.050 0.075 0.10 0.15 0.20 0.25 0.30 0.40 0.50 0.75 1.0 1.5 2.0 3.0 4.0 5.0];
T1 = max(Periods(Periods < T));
T2 = min(Periods(Periods > T));
if min(abs(Periods-T))<1e-4
    T1 = T-1e-4;
    T2 = T+1e-4;
end

%% between-event standard deviation
tauLnSdi_low = nan(size(Cy));
tauLnSdi_high = nan(size(Cy));
Cy_discrete = unique(para_stdNonCond.Cy);
Damp_discrete = unique(para_stdNonCond.Damping);
for i_Cy = 1:length(Cy_discrete)-1
    % short period case
    ip_low = abs(para_stdNonCond.Period-T1)<1e-4 &...
        contains(para_stdNonCond.Component, RotType) &...
        contains(para_stdNonCond.Hysteresis, HysType);
    x1 = log(Cy_discrete(i_Cy));  x2 = log(Cy_discrete(i_Cy+1));
    y1 = log(Damp_discrete(1));  y2 = log(Damp_discrete(2));
    fx1y1 =  para_stdNonCond.tau(ip_low &...
        abs(para_stdNonCond.Damping-Damp_discrete(1))<1e-4 &...
        abs(para_stdNonCond.Cy-Cy_discrete(i_Cy))<1e-4);
    fx2y1 =  para_stdNonCond.tau(ip_low &...
        abs(para_stdNonCond.Damping-Damp_discrete(1))<1e-4 &...
        abs(para_stdNonCond.Cy-Cy_discrete(i_Cy+1))<1e-4);
    fx1y2 =  para_stdNonCond.tau(ip_low &...
        abs(para_stdNonCond.Damping-Damp_discrete(2))<1e-4 &...
        abs(para_stdNonCond.Cy-Cy_discrete(i_Cy))<1e-4);
    fx2y2 =  para_stdNonCond.tau(ip_low &...
        abs(para_stdNonCond.Damping-Damp_discrete(2))<1e-4 &...
        abs(para_stdNonCond.Cy-Cy_discrete(i_Cy+1))<1e-4);
    id_data = Cy>=Cy_discrete(i_Cy) & Cy<=Cy_discrete(i_Cy+1);
    x = log(Cy(id_data));
    y = log(Damping(id_data));
    tauLnSdi_low(id_data) = 1./(x2-x1)./(y2-y1).*(fx1y1.*(x2-x).*(y2-y)+...
        fx2y1.*(x-x1).*(y2-y)+fx1y2.*(x2-x).*(y-y1)+fx2y2.*(x-x1).*(y-y1));
    
    % long period case
    ip_high = abs(para_stdNonCond.Period-T2)<1e-4 &...
        contains(para_stdNonCond.Component, RotType) &...
        contains(para_stdNonCond.Hysteresis, HysType);
    x1 = log(Cy_discrete(i_Cy));  x2 = log(Cy_discrete(i_Cy+1));
    y1 = log(Damp_discrete(1));  y2 = log(Damp_discrete(2));
    fx1y1 =  para_stdNonCond.tau(ip_high &...
        abs(para_stdNonCond.Damping-Damp_discrete(1))<1e-4 &...
        abs(para_stdNonCond.Cy-Cy_discrete(i_Cy))<1e-4);
    fx2y1 =  para_stdNonCond.tau(ip_high &...
        abs(para_stdNonCond.Damping-Damp_discrete(1))<1e-4 &...
        abs(para_stdNonCond.Cy-Cy_discrete(i_Cy+1))<1e-4);
    fx1y2 =  para_stdNonCond.tau(ip_high &...
        abs(para_stdNonCond.Damping-Damp_discrete(2))<1e-4 &...
        abs(para_stdNonCond.Cy-Cy_discrete(i_Cy))<1e-4);
    fx2y2 =  para_stdNonCond.tau(ip_high &...
        abs(para_stdNonCond.Damping-Damp_discrete(2))<1e-4 &...
        abs(para_stdNonCond.Cy-Cy_discrete(i_Cy+1))<1e-4);
    
    id_data = Cy>=Cy_discrete(i_Cy) & Cy<=Cy_discrete(i_Cy+1);
    x = log(Cy(id_data));
    y = log(Damping(id_data));
    tauLnSdi_high(id_data) = 1./(x2-x1)./(y2-y1).*(fx1y1.*(x2-x).*(y2-y)+...
        fx2y1.*(x-x1).*(y2-y)+fx1y2.*(x2-x).*(y-y1)+fx2y2.*(x-x1).*(y-y1));
end
tauLnSdi = tauLnSdi_low+(log(T)-log(T1))./(log(T2)-log(T1)).*(tauLnSdi_high-tauLnSdi_low);

%% within-event standard deviation
phiLnSdi_low = nan(size(Cy));
phiLnSdi_high = nan(size(Cy));
Cy_discrete = unique(para_stdNonCond.Cy);
Damp_discrete = unique(para_stdNonCond.Damping);
for i_Cy = 1:length(Cy_discrete)-1
    % short period case
    ip_low = abs(para_stdNonCond.Period-T1)<1e-4 &...
        contains(para_stdNonCond.Component, RotType) &...
        contains(para_stdNonCond.Hysteresis, HysType);
    x1 = log(Cy_discrete(i_Cy));  x2 = log(Cy_discrete(i_Cy+1));
    y1 = log(Damp_discrete(1));  y2 = log(Damp_discrete(2));
    fx1y1 =  para_stdNonCond.tau(ip_low &...
        abs(para_stdNonCond.Damping-Damp_discrete(1))<1e-4 &...
        abs(para_stdNonCond.Cy-Cy_discrete(i_Cy))<1e-4);
    fx2y1 =  para_stdNonCond.tau(ip_low &...
        abs(para_stdNonCond.Damping-Damp_discrete(1))<1e-4 &...
        abs(para_stdNonCond.Cy-Cy_discrete(i_Cy+1))<1e-4);
    fx1y2 =  para_stdNonCond.phi(ip_low &...
        abs(para_stdNonCond.Damping-Damp_discrete(2))<1e-4 &...
        abs(para_stdNonCond.Cy-Cy_discrete(i_Cy))<1e-4);
    fx2y2 =  para_stdNonCond.phi(ip_low &...
        abs(para_stdNonCond.Damping-Damp_discrete(2))<1e-4 &...
        abs(para_stdNonCond.Cy-Cy_discrete(i_Cy+1))<1e-4);
    id_data = Cy>=Cy_discrete(i_Cy) & Cy<=Cy_discrete(i_Cy+1);
    x = log(Cy(id_data));
    y = log(Damping(id_data));
    phiLnSdi_low(id_data) = 1./(x2-x1)./(y2-y1).*(fx1y1.*(x2-x).*(y2-y)+...
        fx2y1.*(x-x1).*(y2-y)+fx1y2.*(x2-x).*(y-y1)+fx2y2.*(x-x1).*(y-y1));
    
    % long period case
    ip_high = abs(para_stdNonCond.Period-T2)<1e-4 &...
        contains(para_stdNonCond.Component, RotType) &...
        contains(para_stdNonCond.Hysteresis, HysType);
    x1 = log(Cy_discrete(i_Cy));  x2 = log(Cy_discrete(i_Cy+1));
    y1 = log(Damp_discrete(1));  y2 = log(Damp_discrete(2));
    fx1y1 =  para_stdNonCond.phi(ip_high &...
        abs(para_stdNonCond.Damping-Damp_discrete(1))<1e-4 &...
        abs(para_stdNonCond.Cy-Cy_discrete(i_Cy))<1e-4);
    fx2y1 =  para_stdNonCond.phi(ip_high &...
        abs(para_stdNonCond.Damping-Damp_discrete(1))<1e-4 &...
        abs(para_stdNonCond.Cy-Cy_discrete(i_Cy+1))<1e-4);
    fx1y2 =  para_stdNonCond.phi(ip_high &...
        abs(para_stdNonCond.Damping-Damp_discrete(2))<1e-4 &...
        abs(para_stdNonCond.Cy-Cy_discrete(i_Cy))<1e-4);
    fx2y2 =  para_stdNonCond.phi(ip_high &...
        abs(para_stdNonCond.Damping-Damp_discrete(2))<1e-4 &...
        abs(para_stdNonCond.Cy-Cy_discrete(i_Cy+1))<1e-4);
    
    id_data = Cy>=Cy_discrete(i_Cy) & Cy<=Cy_discrete(i_Cy+1);
    x = log(Cy(id_data));
    y = log(Damping(id_data));
    phiLnSdi_high(id_data) = 1./(x2-x1)./(y2-y1).*(fx1y1.*(x2-x).*(y2-y)+...
        fx2y1.*(x-x1).*(y2-y)+fx1y2.*(x2-x).*(y-y1)+fx2y2.*(x-x1).*(y-y1));
end
phiLnSdi = phiLnSdi_low+(log(T)-log(T1))./(log(T2)-log(T1)).*(phiLnSdi_high-phiLnSdi_low);

